services:
  api:
    container_name: "api"
    build: .
    volumes:
      - ./db:/root/db
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    logging:
      driver: json-file
      options:
        max-size: "32m"
        max-file: "3"
