services:
  api:
    container_name: "api"
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "32m"
        max-file: "3"
