BEGIN;

DROP TABLE IF EXISTS sms CASCADE;
DROP TABLE IF EXISTS activations CASCADE;
DROP TABLE IF EXISTS phone_numbers CASCADE;
DROP TABLE IF EXISTS activations_statuses CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS countries CASCADE;

COMMIT;