DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS phone_numbers;
DROP TABLE IF EXISTS activations;
DROP TABLE IF EXISTS activations_statuses;
DROP TABLE IF EXISTS sms;